In [8]:
!pip install PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 1.8 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [14]:
import tabula
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, HTML
from google.colab import files
from io import BytesIO

# Function to extract tables from PDF
def extract_tables(file_content, selected_pages):
    tables = tabula.read_pdf(BytesIO(file_content), pages=selected_pages, multiple_tables=True)
    return tables

# Function to handle file upload and table extraction
def handle_file_upload(change):
    # Get the uploaded file content
    uploaded_file = next(iter(change.new.values()))
    file_content = uploaded_file['content']

    # Create a text input for the user to specify the page numbers
    page_numbers_text = widgets.Text(
        value='',
        placeholder='Enter page numbers (e.g., 1-3,5,7)',
        description='Page Numbers:',
        disabled=False,
        layout=widgets.Layout(width='50%')
    )

    # Display the text input widget
    display(page_numbers_text)

    # Define a function to handle table extraction when the user specifies the page numbers
    def on_page_numbers_specified(change):
        page_numbers = change.new
        selected_pages = parse_page_numbers(page_numbers)
        tables = extract_tables(file_content, selected_pages)
        for i, table in enumerate(tables):
            # Save the table as a CSV file
            csv_file = f"table_{i+1}.csv"
            table.to_csv(csv_file, index=False)
            print(f"Table {i+1} saved to {csv_file}")

            # Display a preview of the table
            print(f"\nPreview of table {i+1}:\n")
            display(HTML(table.to_html()))

    # Register the function to handle the specified page numbers
    page_numbers_text.observe(on_page_numbers_specified, names='value')

# Function to parse the user input of page numbers
def parse_page_numbers(page_numbers):
    selected_pages = []
    ranges = page_numbers.split(',')
    for rng in ranges:
        if '-' in rng:
            start, end = map(int, rng.split('-'))
            selected_pages.extend(range(start, end + 1))
        else:
            selected_pages.append(int(rng))
    return selected_pages

# Create a file upload widget
file_upload = widgets.FileUpload()
file_upload.observe(handle_file_upload, names='value')

# Display the file upload widget
display(file_upload)

FileUpload(value={}, description='Upload')

Text(value='', description='Page Numbers:', layout=Layout(width='50%'), placeholder='Enter page numbers (e.g.,…

Table 1 saved to table_1.csv

Preview of table 1:

Table 2 saved to table_2.csv

Preview of table 2:

Table 3 saved to table_3.csv

Preview of table 3:

Table 4 saved to table_4.csv

Preview of table 4:

Table 5 saved to table_5.csv

Preview of table 5:

Table 6 saved to table_6.csv

Preview of table 6: